apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-2048

resources:
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/ingress.yaml
