apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  server.secretkey: F0BUqK8K7wOuT4K7dPsXyEOwOTA4m0tQNCdXyLinKaw=
  admin.passwordMtime: '2023-06-05T08:48:48Z'
  admin.password: $2y$10$RKOaJTo6/gnMc37UrrgOYuV3OEHDRa6Ki34AMc7LcpqMgFSygrko2
