apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-staging
  namespace: argocd
spec:
  source:
    path: multi-stage-example/manifests/podinfo/staging
    repoURL: http://git-repo-server.git-repo-server.svc.cluster.local:/git/manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
